"""empty message

Revision ID: 90618ce755a2
Revises: 51f526650797
Create Date: 2022-11-21 18:53:57.691308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90618ce755a2'
down_revision = '51f526650797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=postgresql.BYTEA(),
               type_=sa.Unicode(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Unicode(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
